### PR TITLE
Pandas multivariate doc update

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Polished first draft on Pandas multivariate dataframe doc update. I didn't add any additional examples since I felt that what we had was already pretty clear--let me know if you see things differently!

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/124)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
sorry for the delayed review. i agree the example is clear

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/124#-:-MSWCH679DBuc3mDlRVR:bceea71)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/pandas/multivariate_dataframe.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWBVul2Hypp9_fgrUo:-MSWBVul2Hypp9_fgrUp:b-a1kdy5) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L9)):*
> ```Markdown
> ---
> 
> # Get Multivariate DataFrame
> ```

Get -> Retrieve?
___
*[api/pandas/multivariate_dataframe.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWBXSQCHpj5aZg63kb:-MSWBXSQCHpj5aZg63kc:btm3u9e) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L20)):*
> ```Markdown
> ## General information about this method
> 
> **Signature**: `datacommons_pandas.build_multivariate_dataframe(places, stat_vars)`
> ```

Use ```python here
___
*[api/pandas/multivariate_dataframe.md, line 35 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWBRpT13_LL94cN0Qp:-MSWBRpT13_LL94cN0Qq:bvby3ve) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L35)):*
> ```Markdown
>  - `places`: Data Commons uniquely identifies nodes by assigning them DCIDs, or Data Commons IDs. Your query will need to specify the DCIDs for the nodes of interest.
> 
>  - `stat_vars`: This argument specifies the types of places sought in the response. For example, when examining places contained within American `States`, you would be able to select `City` or `County` (among others). For a full list of available types, see [`subClassOf Place`](https://datacommons.org/browser/Place.
> ```

There's a formatting error with the last link
___
*[api/pandas/multivariate_dataframe.md, line 53 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWC5FSByqDULMOgl52:-MSWC5FSByqDULMOgl53:b-mbst8g) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L53)):*
> ```Markdown
> 
> ```python
> >>> datacommons_pandas.build_multivariate_dataframe(["country/USA", "geoId/06", "geoId/123123123123123123"],["Count_Person", "Median_Age_Person", "UnemploymentRate_Person"])
> ```

maybe we can make it clearer that geoId/123123123123  is the unknown place? i initially thought there was an error as this looked like a duplicate of the example above.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/124)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

___
*[api/pandas/multivariate_dataframe.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWBVul2Hypp9_fgrUo:-MSpcePh3tur3RvoKEH0:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Get -> Retrieve?
</blockquote></details>

Done.
___
*[api/pandas/multivariate_dataframe.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWBXSQCHpj5aZg63kb:-MSpcjB89X1Hf0EQ8ky6:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L20)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Use ```python here
</blockquote></details>

Done.
___
*[api/pandas/multivariate_dataframe.md, line 35 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWBRpT13_LL94cN0Qp:-MSpcm7DCxLMxaVfnOiS:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L35)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

There's a formatting error with the last link
</blockquote></details>

Done.
___
*[api/pandas/multivariate_dataframe.md, line 53 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/124#-MSWC5FSByqDULMOgl52:-MSpd-bt3yNfJ4X953tq:b-43qes5) ([raw file](https://github.com/datacommonsorg/docsite/blob/f9fc4944c7d77e8b18f86ed72fa3947fa8a37def/api/pandas/multivariate_dataframe.md#L53)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

maybe we can make it clearer that geoId/123123123123  is the unknown place? i initially thought there was an error as this looked like a duplicate of the example above.
</blockquote></details>

I added language to indicate that this is the unknown place.

**Review by beets — COMMENTED** [review]
looks good! merging :)

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/124#-:-MT6wM2g-v2pvo9TlkHJ:b-kccmih)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tjann)

**Review by beets — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/124#-:-MT6wO_a4uB_-PZkcflC:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tjann)

**Pull request merged**
