### PR TITLE
Polished first draft on 'Places within a Place' REST docs

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Revamping the docs for `node/places-in` endpoint.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)

### CODE REVIEW

**Review by tjann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/place_in.md, line 12 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-DZk0BzS5wr8wbA0:-MO3-DZk0BzS5wr8wbA1:bz5ny2r) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L12)):*
> ```Markdown
> 
> Given a list of parent [`Place`](https://datacommons.org/browser/Place) DCIDs,
> (e.g. `County`, `State`, `Country`, etc...), return a list of child places
> ```

nit: 

```
e.g. any [`State`](https://datacommons.org/browser/State), [`Country`](https://datacommons.org/browser/Country], etc.)
```
___
*[api/rest/place_in.md, line 28 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-uek9qdm8tp_gnBZ:-MO3-uek9qdm8tp_gnB_:b-piam0p) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L28)):*
> ```Markdown
> *   `dcids`: A list of (parent) places, identified by their DCIDs.
> 
> *   `placeType`: The type of the contained (child) `Places` to filter by. For example, `City` and `County` are contained within `State`. For a
> ```

@kilimannejaro  soliciting your opinion on how we might decide when to use just "place" and "places" vs "`Place`" and "`Places`"? At least here, I would think the dcids and placeType descriptions should be consistent. But maybe that is too nit picky
___
*[api/rest/place_in.md, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-iyL20kfcqRTm_aw:-MO3-iyL20kfcqRTm_ax:bb4iqor) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L33)):*
> ```Markdown
> **Optional Arguments**:
> 
> *   `key`: Your API key.
> ```

Could you sync this and other PRs to master, to reflect the latest change by cyin removing the API key references?
___
*[api/rest/place_in.md, line 43 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO30L6X6yrIff4ei0i5:-MO30L6X6yrIff4ei0i6:b-m75aq) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L43)):*
> ```Markdown
> This endpoint also requires the argument `placeType`, specifying the type of the child places you desire in the response.
> 
> In addition to these required properties, this endpoint also allows you to specify your API key as an optional argument.
> ```

This line is obsolete now, sorry!
___
*[api/rest/place_in.md, line 68 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3NsYDAmDPM7jGkCF-:-MO3NsYDAmDPM7jGkCF0:b-zflsto) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L68)):*
> ```Markdown
>   },
>   ...
> ]
> ```

instead of just "string", which I find odd since the quotes themselves indicate string, could we do
"dcid": "stringOfParentPlaceDCID",
"place": "stringOfChildPlaceDCID"
___
*[api/rest/place_in.md, line 167 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3OixY7B0TryJaTkkx:-MO3OixY7B0TryJaTkky:bgk7l2o) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L167)):*
> ```Markdown
> ## Error Responses
> 
> In general, if your request is malformed in some way, you will receive a 400 status code and an error message like the following:
> ```

Just wondering if we can just start with "If your request"

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/place_in.md, line 28 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-uek9qdm8tp_gnBZ:-MO4h-cl48bykTRqcic3:bogqiqg) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L28)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

@kilimannejaro  soliciting your opinion on how we might decide when to use just "place" and "places" vs "`Place`" and "`Places`"? At least here, I would think the dcids and placeType descriptions should be consistent. But maybe that is too nit picky
</blockquote></details>

@tjann thanks for this comment--and it's absolutely not nitpicky! So I would say that `Place` should refer to the Data Commons object specifically, while place refers to a location or a position more generally. Here are two example sentences:

Sarah loves travelling to many new places.
Sarah should call the API by specifying DCIDs associated with the `Places` whose populations she wishes to measure.

As such, I fully agree that here we should see some consistency, and I will update to reflect that.

As an aside, for matters like this, would it be useful if I created a style guide or generally a decision document somewhere?
___
*[api/rest/place_in.md, line 68 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3NsYDAmDPM7jGkCF-:-MO4isHi42ry7l6iM1bb:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L68)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

instead of just "string", which I find odd since the quotes themselves indicate string, could we do
"dcid": "stringOfParentPlaceDCID",
"place": "stringOfChildPlaceDCID"
</blockquote></details>

Done.
___
*[api/rest/place_in.md, line 167 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3OixY7B0TryJaTkkx:-MO4ixcjAt8ZzV29Z50v:b8f3gvc) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L167)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

Just wondering if we can just start with "If your request"
</blockquote></details>

I am not sure what is meant by this. Would you like for me to remove the words 'in some way'?

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/place_in.md, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-iyL20kfcqRTm_aw:-MO4lWmABkgo3yphzfKv:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L33)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

Could you sync this and other PRs to master, to reflect the latest change by cyin removing the API key references?
</blockquote></details>

Done.
___
*[api/rest/place_in.md, line 43 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO30L6X6yrIff4ei0i5:-MO4lUgc-tUQj0GSeYC2:bss4a2b) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L43)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

This line is obsolete now, sorry!
</blockquote></details>

Removed.

**Review by tjann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/place_in.md, line 28 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-uek9qdm8tp_gnBZ:-MO8qiIW9jfc7Esai185:bmsarkm) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L28)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

@tjann thanks for this comment--and it's absolutely not nitpicky! So I would say that `Place` should refer to the Data Commons object specifically, while place refers to a location or a position more generally. Here are two example sentences:

Sarah loves travelling to many new places.
Sarah should call the API by specifying DCIDs associated with the `Places` whose populations she wishes to measure.

As such, I fully agree that here we should see some consistency, and I will update to reflect that.

As an aside, for matters like this, would it be useful if I created a style guide or generally a decision document somewhere?
</blockquote></details>

Got it, I agree. I had a semi related comment in one of your PRs that we should be clear about using `Place`s instead of `Places`, since when we have code-face, we are trying to be the most accurate, as if there will be a compile error :laughing: 

Yeah, that's a great idea! Were you thinking https://github.com/datacommonsorg/docsite/blob/master/README.md or somewhere else?
___
*[api/rest/place_in.md, line 167 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3OixY7B0TryJaTkkx:-MO8t3UO6Vyy-Eb7IvBs:b-d76gyx) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L167)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I am not sure what is meant by this. Would you like for me to remove the words 'in some way'?
</blockquote></details>

You made the change I was suggesting! But removing in some way is fine with me. Up to you :) 
___
*[api/rest/place_in.md, line 74 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO8tLsbCfA_HKE0Hbaz:-MO8tLsbCfA_HKE0Hbb-:b-2ddtgm) ([raw file](https://github.com/datacommonsorg/docsite/blob/459287d1bf97a6478d1889d5d8d8532c276ece1b/api/rest/place_in.md#L74)):*
> ```Markdown
> <div>
> 
> {% tabs log %}
> ```

Just want to say that this tab thing is awesome, especially having both tab and JSFiddle. Thanks so much for pioneering this!

**Comment by tjann** [comment]
I wasn't able to leave a high level comment on Reviewable. @KilimAnnejaro I'll approve this PR after the `Places` -> `Place`s and similar changes!

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/place_in.md, line 28 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-uek9qdm8tp_gnBZ:-MO9cQAO2Rny9eV8nHCd:bt1cw46) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L28)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

Got it, I agree. I had a semi related comment in one of your PRs that we should be clear about using `Place`s instead of `Places`, since when we have code-face, we are trying to be the most accurate, as if there will be a compile error :laughing: 

Yeah, that's a great idea! Were you thinking https://github.com/datacommonsorg/docsite/blob/master/README.md or somewhere else?
</blockquote></details>

OK. The Google style guide specifically proscribes writing this type of plural in documentation: https://developers.google.com/style/code-in-text
I reworded the sentence to avoid the issue; let me know what you think!
___
*[api/rest/place_in.md, line 74 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO8tLsbCfA_HKE0Hbaz:-MO9dlnhBM-EMJ4HO4Ln:bwrlada) ([raw file](https://github.com/datacommonsorg/docsite/blob/459287d1bf97a6478d1889d5d8d8532c276ece1b/api/rest/place_in.md#L74)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

Just want to say that this tab thing is awesome, especially having both tab and JSFiddle. Thanks so much for pioneering this!
</blockquote></details>

Thanks! That really means a lot to me :heart:

**Review by beets — CHANGES_REQUESTED** [review]
Thanks for the update! A couple of small changes requested...

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97#-:-MQIodiW62aQ5fycMpvK:b-ntiig2)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/rest/place_in.md, line 28 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MO3-uek9qdm8tp_gnBZ:-MQInyuxEjfbrBcNGeta:b-2ooew9) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L28)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

OK. The Google style guide specifically proscribes writing this type of plural in documentation: https://developers.google.com/style/code-in-text
I reworded the sentence to avoid the issue; let me know what you think!
</blockquote></details>

Got it - thanks for pointing to the style guide! Avoiding the issue sounds good.
___
*[api/rest/place_in.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MMvQ77c446je75USDYL:-MMvQ77c446je75USDYM:b5byp0z) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L47)):*
> ```Markdown
> ### Step 2: creating the request
> 
> When actually putting together your request, you can choose from two options. If you intend to query only a small number of DCIDs, you may want to use the simpler formatting offered by the GET method. For larger numbers of DCIDs, or if you prefer to utilize a static URL, a POST request likely makes more sense. To use it, make a POST request against the main endpoint while changing the fields of the JSON body it sends.
> ```

Perhaps we can refer them to examples of each below.
___
*[api/rest/place_in.md, line 80 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MMvQbcK9f3qDo3kploB:-MMvQbcK9f3qDo3kploC:b-oezpsv) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L80)):*
> ```Markdown
> #### GET Request
> 
> ```curl
> ```

replace curl with bash - there isn't a curl formatter, but there is for bash and will provide some syntax highlighting.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/place_in.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MMvQ77c446je75USDYL:-MQKngiO803maiQtytmO:ba5xy1u) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L47)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Perhaps we can refer them to examples of each below.
</blockquote></details>

I added a sentence here to direct readers to the examples we have below. Let me know if you'd like to see something different!
___
*[api/rest/place_in.md, line 80 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/97#-MMvQbcK9f3qDo3kploB:-MQKnNUOA2Zwa4BG6AUP:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b3e6559e1cfdd6b8906b0668cff80c11e1333d18/api/rest/place_in.md#L80)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

replace curl with bash - there isn't a curl formatter, but there is for bash and will provide some syntax highlighting.
</blockquote></details>

Done.

**Review by beets — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/97)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

**Review by tjann — APPROVED** [review]

**Pull request merged**
