### PR TITLE
First pass on overhauling documentation for Python SPARQL method

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Edit/comment access for the Colab notebook available on request. I also wasn't sure if incorporating error returns into that particular notebook was the best strategy--open to suggestions!

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/141)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
I think the colab notebook is great - though it would be nice if those examples were folded in here as well, just like we have for the other API's (opening the colab seems very heavy weight). We should add a header in the colab referencing the API doc too.

For the examples there with errors, it would be nice to point out what's missing / what the error was, and what changes are required to get it working again. I think those are great teaching moments.

I also think carrying over the "what to expect in the response" section from other API docs would be good to have here.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/141#-:-MSW99uj1c98L181olG0:bd7kf51)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KilimAnnejaro)

___
*[api/python/query.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/141#-MSW9V-O2puEOUWFhwpB:-MSW9V-O2puEOUWFhwpC:bz92mdx) ([raw file](https://github.com/datacommonsorg/docsite/blob/a2f453bbe0ec3285285864f09d99265709f30206/api/python/query.md#L9)):*
> ```Markdown
> ---
> 
> # Query the Data Commons knowledge graph using SPARQL
> ```

Please use "Data Commons Graph" (we reference it that way in the home page. I noticed the REST SPARQL doc should be updated with this as well - thanks!

**Review by KilimAnnejaro — COMMENTED** [review]
I've updated the notebook to provide coaching and information on the errors. I also added a "what to expect in the response" in this doc.
With regards to the colab notebook: do you want me to add the examples inline as markdown, in addition to providing the colab?

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/141#-:-MSsy7yyAVkiQUCkFZED:b-27adrv)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @beets)

___
*[api/python/query.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/141#-MSW9V-O2puEOUWFhwpB:-MSskeBw-VSjVZk-ne9w:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/a2f453bbe0ec3285285864f09d99265709f30206/api/python/query.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please use "Data Commons Graph" (we reference it that way in the home page. I noticed the REST SPARQL doc should be updated with this as well - thanks!
</blockquote></details>

Done.

**Review by beets — COMMENTED** [review]
Yes, I think it would be good to have the examples inline here, so this doc can be the source of truth. We've found it difficult to maintain colab notebooks in the past. If that's too troublesome, we can port some of the examples, and add a link to the colab for the rest.

I really like the walkthrough at the end of the notebook to fix the error!

Example 5 might be more helpful if we also retrieved the date for each observation

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/141#-:-MT76HtAAPz5lGMkIxaX:b-94pk30)* status: 0 of 1 files reviewed, all discussions resolved

**Review by KilimAnnejaro — COMMENTED** [review]
Hi Carolyn, I've responded to these comments in the most recent edition--please take a look and let me know what you think!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/141#-:-MTSjyx39I0gQWawGSx1:b-60qt7d)* status: 0 of 1 files reviewed, all discussions resolved

**Review by beets — APPROVED** [review]

**Comment by beets** [comment]
this is awesome - thanks for adding the examples!

**Pull request merged**
