### PR TITLE
Stat value REST docs update

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Updating the REST docs for the stat value endpoint.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
Some of the diffs here should be resolved by updating the branch to HEAD

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102#-:-MO3IDea2PYgNVjn5CfI:b5bdnzm)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/stat_value.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3CpkC5mUrVgwuKopk:-MO3CpkC5mUrVgwuKopl:baqmc0b) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L9)):*
> ```Markdown
> ---
> 
> # Retrieve statistical value for a place
> ```

Since we return a single value, maybe: "Return a statistical value for a place"
___
*[api/rest/stat_value.md, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3D0Tk51DDtWuIcmHn:-MO3D0Tk51DDtWuIcmHo:b-cuvg1d) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L16)):*
> ```
> more authorative
> ```

Maybe: more authority?
___
*[api/rest/stat_value.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FPs95PImuAI-2Gc7:-MO3FPs95PImuAI-2Gc8:bvtn9hk) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L47)):*
> ```Markdown
> Going into more detail on how to assemble the values for the required arguments:
> 
>  - `place`: For this parameter, you will need to specify the DCID (the unique ID assigned by Data Commons to each node in the graph) of the place you are interested in.
> ```

Let's work on getting the glossary in, so that we can start referring to it here.. and so we won't have to duplicate the descriptions.

@tjann 
___
*[api/rest/stat_value.md, line 54 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FRwJ1yyLx4BMRs1t:-MO3FRwJ1yyLx4BMRs1u:b4e1gxm) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L54)):*
> ```Markdown
>   - `date`: Specified in ISO 8601 format. Examples include `2011` (the year 2011), `2019-06` (the month of June in the year 2019), and `2019-06-05T17:21:00-06:00` (5:17PM on June 5, 2019, in CST).
> 
>   - `measurement_method`: The technique used for measuring a statistical variable. Describes how a measurement is made, whether by count or estimate or some other approach, and names the group making the measurement. Examples include `BosniaCensus` and [`WorldHealthOrganizationEstimates`](https://datacommons.org/browser/WorldHealthOrganizationEstimates).
> ```

See comment on #99 regarding dropping BosniaCensus and maybe adding CensusACS5YearSurvey
___
*[api/rest/stat_value.md, line 88 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3G6pr3HBLLLXaHnee:-MO3G6pr3HBLLLXaHnef:b-xqzk3l) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L88)):*
> ```
> %2F
> ```
Might be easier to keep the "/", here and below
___
*[api/rest/stat_value.md, line 101 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3G-Ht5W_dWxz5Wtmt:-MO3G-Ht5W_dWxz5Wtmu:bbmfxb9) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L101)):*
> ```Markdown
> {% endtabs %}
> 
> <script src="/assets/js/tabs.js"></script>
> ```

This isn't needed anymore since we are adding that to the default layout.
___
*[api/rest/stat_value.md, line 127 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3I-S20vgVdOjDtEGc:-MO3I-S20vgVdOjDtEGd:b-yl626v) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L127)):*
> ```Markdown
> {% endtabs %}
> 
> <script src="/assets/js/tabs.js"></script>
> ```

We shouldn't include the same source multiple times per page...
___
*[api/rest/stat_value.md, line 181 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3I6Si1B_q-b4qvuXr:-MO3I6Si1B_q-b4qvuXs:bgobffa) ([raw file](https://github.com/datacommonsorg/docsite/blob/1e89a72f69cc4c3293f7572f21d89632e86146d3/api/rest/stat_value.md#L181)):*
> ```
> naloxone
> ```
the drug Naloxone

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/stat_value.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3CpkC5mUrVgwuKopk:-MO9qkdXAeSOTtj7FGEf:byx76bs) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Since we return a single value, maybe: "Return a statistical value for a place"
</blockquote></details>

Yep, that makes sense! One comment: I prefer the word 'retrieve' for the header, since we would be using 'returns' again almost immediately in the following line.
___
*[api/rest/stat_value.md, line 16 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3D0Tk51DDtWuIcmHn:-MO9n-Tm3QC5Zcd7ft0G:b-oz8tyz) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L16)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> more authorative
> ```

Maybe: more authority?
</blockquote></details>

Good call!
___
*[api/rest/stat_value.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FPs95PImuAI-2Gc7:-MO9o2P6-dtpKWW9ohgc:bop15pw) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L47)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Let's work on getting the glossary in, so that we can start referring to it here.. and so we won't have to duplicate the descriptions.

@tjann 
</blockquote></details>

Work in progress! :smiley: 
___
*[api/rest/stat_value.md, line 54 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FRwJ1yyLx4BMRs1t:-MO9nzupDfJ0JjEPSI1k:b-ps0x9r) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L54)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

See comment on #99 regarding dropping BosniaCensus and maybe adding CensusACS5YearSurvey
</blockquote></details>

As a stopgap measure, I copied the definition from that PR. Once the glossary gets published, we will be able to move towards linking to the definition instead.
___
*[api/rest/stat_value.md, line 88 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3G6pr3HBLLLXaHnee:-MO9oZnG4ZPzgRb1-l3s:bnj77n1) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L88)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> %2F
> ```
Might be easier to keep the "/", here and below
</blockquote></details>

I replaced all the %2F instances, here and below.
___
*[api/rest/stat_value.md, line 101 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3G-Ht5W_dWxz5Wtmt:-MO9r7qE1uiUzmR2j3Cg:bss4a1y) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L101)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

This isn't needed anymore since we are adding that to the default layout.
</blockquote></details>

Removed!
___
*[api/rest/stat_value.md, line 127 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3I-S20vgVdOjDtEGc:-MO9owzf0E8BWM-J-Ha3:bk0lmcj) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L127)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We shouldn't include the same source multiple times per page...
</blockquote></details>

Oh great, I'm sorry about that! I removed all these tags on this PR.
___
*[api/rest/stat_value.md, line 181 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3I6Si1B_q-b4qvuXr:-MO9pYNc3aWO7nyJm40Y:b-41t5u0) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L181)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> naloxone
> ```
the drug Naloxone
</blockquote></details>

Done. Also, since naloxone is a generic drug, rather than a brand name (like Narcan), so it should not be capitalized. See https://nwtc.libanswers.com/faq/212916#:~:text=APA%20rules%20for%20proper%20nouns,Advil%20vs%20ibuprofen.

**Review by beets — CHANGES_REQUESTED** [review]
Thanks for the updates! Just a couple of smaller updates requested now that the glossary is in.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102#-:-MQIrArXBr_QggUItbAW:bb70po6)* status: all files reviewed, 2 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/rest/stat_value.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FPs95PImuAI-2Gc7:-MQIpIuU2MmKGmkQec2p:b-lsbjbu) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L47)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Work in progress! :smiley: 
</blockquote></details>

Now that it's in, can we update this? (and we should refer to it the same way throughout the docs). 
___
*[api/rest/stat_value.md, line 54 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FRwJ1yyLx4BMRs1t:-MQIqv-V4Hx-oq7ARmDI:b-kuby0t) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L54)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

As a stopgap measure, I copied the definition from that PR. Once the glossary gets published, we will be able to move towards linking to the definition instead.
</blockquote></details>

Now that the glossary is in, should we update this? Thanks and sorry for the delay on this PR!
___
*[api/rest/stat_value.md, line 181 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3I6Si1B_q-b4qvuXr:-MQIr4dYA__w5lNkPFJD:b-qtlmed) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L181)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done. Also, since naloxone is a generic drug, rather than a brand name (like Narcan), so it should not be capitalized. See https://nwtc.libanswers.com/faq/212916#:~:text=APA%20rules%20for%20proper%20nouns,Advil%20vs%20ibuprofen.
</blockquote></details>

Oh thanks for looking it up! Sounds good.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: all files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/stat_value.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FPs95PImuAI-2Gc7:-MQKwphd41ZPLsojzPHR:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L47)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Now that it's in, can we update this? (and we should refer to it the same way throughout the docs). 
</blockquote></details>

Done.
___
*[api/rest/stat_value.md, line 54 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MO3FRwJ1yyLx4BMRs1t:-MQKws-PErYAn7Av1fTb:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/07d1b00410d2f18ebeb469189680dd83c7dbfc02/api/rest/stat_value.md#L54)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Now that the glossary is in, should we update this? Thanks and sorry for the delay on this PR!
</blockquote></details>

Done.

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/stat_value.md, line 52 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvUiR91Nf9xlqokHr:-MQNvUiS4kXeY-5mgvkJ:b-aw5bqz) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L52)):*
> ```Markdown
> In addition to these required properties, this endpoint also allows for other, optional arguments. Here are helpful arguments in regular use by Data Commons developers:
> 
>   - [`date`](https://docs.datacommons.org/glossary.html): The date of the desired statistical value, specified in ISO 8601 format.
> ```

There isn't an entry in the glossary for date, so we might want to keep the old description here.
___
*[api/rest/stat_value.md, line 56 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvdb5CCuDZU31Sp0E:-MQNvdb5CCuDZU31Sp0F:b747y3y) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L56)):*
> ```Markdown
>   - [`measurement_method`](https://docs.datacommons.org/glossary.html): The technique used for measuring a statistical variable.
>   
>   - [`observation_period`](https://docs.datacommons.org/glossary.html): The time period over which an observation is made.
> ```

I noticed that the entry for observation period in the glossary could use more details, specifically how it uses the ISO 8601 Duration formatting
https://en.wikipedia.org/wiki/ISO_8601#Durations

Could you update the description there and mention it briefly here? Thanks!

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/stat_value.md, line 52 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvUiR91Nf9xlqokHr:-MQQ-zQj0SHO56bZcgrX:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L52)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

There isn't an entry in the glossary for date, so we might want to keep the old description here.
</blockquote></details>

Done.
___
*[api/rest/stat_value.md, line 56 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvdb5CCuDZU31Sp0E:-MQQ0D4MBCSnTl72yqa7:b4hwi5a) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L56)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

I noticed that the entry for observation period in the glossary could use more details, specifically how it uses the ISO 8601 Duration formatting
https://en.wikipedia.org/wiki/ISO_8601#Durations

Could you update the description there and mention it briefly here? Thanks!
</blockquote></details>

Yep! I will submit a PR.

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/stat_value.md, line 52 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvUiR91Nf9xlqokHr:-MQTrgFGCgEOi-yZUzY9:bphr54v) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L52)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we can now link to the glossary for this field too :)
___
*[api/rest/stat_value.md, line 56 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvdb5CCuDZU31Sp0E:-MQTrO5S5Tyk-JgS50D7:b-ucfknh) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L56)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Yep! I will submit a PR.
</blockquote></details>

Thanks!

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @beets and @tjann)

___
*[api/rest/stat_value.md, line 52 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/102#-MQNvUiR91Nf9xlqokHr:-MQUqY_Z1v7jtH_1dtuN:b-dso4o2) ([raw file](https://github.com/datacommonsorg/docsite/blob/de11d367cabbf45810360dde6626ce2570a6c493/api/rest/stat_value.md#L52)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

we can now link to the glossary for this field too :)
</blockquote></details>

HOORAY! Done :-)

**Review by beets — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjann)

**Pull request merged**
