### PR TITLE
Python property value

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Updating the Python property value docs.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)

### CODE REVIEW

**Review by tjann — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/property_value.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3TNz1DUKlpsA6kGuO:-MO3TNz1DUKlpsA6kGuP:b-uzzkkb) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L9)):*
> ```Markdown
> ---
> 
> # Show Property Values for Node(s)
> ```

s/Show/Get
___
*[api/python/property_value.md, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3TchwAPdnIiMUiGRk:-MO3TchwAPdnIiMUiGRl:b7o8qlx) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L22)):*
> ```Markdown
> **Required arguments**:
> 
> *   `dcids`: A list of nodes to query, identified by their DCID.
> ```

Data Commons Identifier (DCID)
___
*[api/python/property_value.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3U1Wo3K-PctagdUr4:-MO3U1Wo3K-PctagdUr5:bo42y7t) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L36)):*
> ```Markdown
> Going into more detail on how to assemble the values for the required arguments:
> 
>  - `dcids`: Data Commons uniquely identifies nodes by assigning them DCIDs, or Data Commons IDs. Your query will need to specify the DCIDs for the nodes of interest.
> ```

I thought it was nice to move the DCID=Data Commons Identifier up, so we may not need it here
___
*[api/python/property_value.md, line 42 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3ayJI8gGrbcD9C7B_:-MO3ayJI8gGrbcD9C7Ba:bxv6wfg) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L42)):*
> ```Markdown
> In addition to these required properties, this endpoint also allows for other, optional arguments. Here are helpful arguments in regular use by Data Commons developers:
> 
>   - `value_type`: If the property queried only takes on node values, you can use this argument to filter nodes in the response, ensuring the response only contains nodes with the specified type.
> ```

I think a reasonable example to make this more concrete is for containedInPlace. E.g. if you do https://api.datacommons.org/node/property-values?dcids=geoId/06085&property=containedInPlace you get loooots of results
https://api.datacommons.org/node/property-values?dcids=geoId/06085&property=containedInPlace&valueType=City will limit it to just typeOf City
___
*[api/python/property_value.md, line 68 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3nIMDAIojL28h6jrO:-MO3nIMDAIojL28h6jrP:b-uupyqe) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L68)):*
> ```
> ```python
> dc.get_property_values(['country/CIV'],'name')
> ```
> ```
___
*[api/python/property_value.md, line 76 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3n18c0TDv_7WtNckD:-MO3n18c0TDv_7WtNckE:b-ogxnrt) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L76)):*
1) I think it's reasonable to just go with the formatted one (since even "raw" does not seem to need parsing in Python)
2) can we keep the Python interpreter format? E.g. instead of theses json blocks, keep it with the above python block, as if you are running in terminal:

Straight out of my terminal:

```
>>> import datacommons as dc
>>> dc.get_property_values(['country/CIV'],'name')
{'country/CIV': ["Côte d'Ivoire", 'Ivory Coast']}
```

can format the result spacing, though
___
*[api/python/property_value.md, line 239 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3ouO4EFx2-XEMUktq:-MO3ouO4EFx2-XEMUktr:bhabxlq) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L239)):*
> ```Markdown
> ## Error Returns
> 
> If there is no value associated with the property, an empty list is returned:
> ```

This could go before ## Error Returns, since it's not really an error

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/property_value.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3TNz1DUKlpsA6kGuO:-MO9ycyHBneCHippQCmK:b62iziq) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L9)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

s/Show/Get
</blockquote></details>

If possible, I prefer the word "retrieve" to get in this context--analogous to https://stripe.com/docs/api/balance/balance_retrieve (and the other Stripe docs), so I updated to that. Let me know if you want to discuss!
___
*[api/python/property_value.md, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3TchwAPdnIiMUiGRk:-MO9yzem2zlMp0VXeLsy:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L22)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

Data Commons Identifier (DCID)
</blockquote></details>

Done.
___
*[api/python/property_value.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3U1Wo3K-PctagdUr4:-MO9z1_-40bDl5F7u5h0:b9rbj0e) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L36)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

I thought it was nice to move the DCID=Data Commons Identifier up, so we may not need it here
</blockquote></details>

Clarify: do you want this definition moved into initial information? Because that would be different in structure from the previous API doc updates.
___
*[api/python/property_value.md, line 68 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3nIMDAIojL28h6jrO:-MO9zIh8-6uILv6_qbZe:b-battds) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L68)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

> ```
> ```python
> dc.get_property_values(['country/CIV'],'name')
> ```
> ```

</blockquote></details>

I am not sure I understand this comment. Would you like an additional line of whitespace here? Thank you!
___
*[api/python/property_value.md, line 76 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3n18c0TDv_7WtNckD:-MO9zYNl9GZPy-1NSDkP:b-7k1gcq) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L76)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

1) I think it's reasonable to just go with the formatted one (since even "raw" does not seem to need parsing in Python)
2) can we keep the Python interpreter format? E.g. instead of theses json blocks, keep it with the above python block, as if you are running in terminal:

Straight out of my terminal:

```
>>> import datacommons as dc
>>> dc.get_property_values(['country/CIV'],'name')
{'country/CIV': ["Côte d'Ivoire", 'Ivory Coast']}
```

can format the result spacing, though
</blockquote></details>

1. I agree and will remove all the headers.
___
*[api/python/property_value.md, line 239 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3ouO4EFx2-XEMUktq:-MOA-Si-3e0chGnPMYeT:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L239)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

This could go before ## Error Returns, since it's not really an error
</blockquote></details>

Done.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/property_value.md, line 42 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3ayJI8gGrbcD9C7B_:-MOS0OLw77Z2sSIHqg28:bxlav8x) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L42)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

I think a reasonable example to make this more concrete is for containedInPlace. E.g. if you do https://api.datacommons.org/node/property-values?dcids=geoId/06085&property=containedInPlace you get loooots of results
https://api.datacommons.org/node/property-values?dcids=geoId/06085&property=containedInPlace&valueType=City will limit it to just typeOf City
</blockquote></details>

I added an explanation here incorporating this example.

**Review by beets — CHANGES_REQUESTED** [review]
Sorry for the late review!

Some comments here on general structure that we could hopefully apply to the rest of the python doc updates...

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107#-:-MQovjWI78VkLj2OrbT3:b4knkv)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/property_value.md, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3TchwAPdnIiMUiGRk:-MQotxwM8yr5NOea7UA5:b-rc8zhe) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L22)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we update to match REST, wrt glossary references?

As an aside, it would be nice to do another pass through the REST docs after they're all in to standardize how we refer to the glossary.
___
*[api/python/property_value.md, line 76 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3n18c0TDv_7WtNckD:-MQoukv7CjOgCRRIFHkw:bijmrw6) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L76)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

1. I agree and will remove all the headers.
</blockquote></details>

+1 to using a single block mirroring an interactive python shell (for here and the rest of the python doc updates)
___
*[api/python/property_value.md, line 16 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MQotQ06E896stV_yWgC:-MQotQ070hfu6EkSXSWC:b-t0cgd) ([raw file](https://github.com/datacommonsorg/docsite/blob/32f240ce842317c35e554d6d5d0408d178981357/api/python/property_value.md#L16)):*
> ```Markdown
> ## General information about this endpoint
> 
> **Signature**: `datacommons.get_property_values(dcids, prop, out=True, value_type=None, limit=datacommons.utils._MAX_LIMIT)`
> ```

Can we try using  
```python
<method signature here>
```

so that we get some syntax highlighting? I think it would really help readability
___
*[api/python/property_value.md, line 18 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MQorlXn9DaTlTkXb2Km:-MQorlXn9DaTlTkXb2Kn:brqooaz) ([raw file](https://github.com/datacommonsorg/docsite/blob/32f240ce842317c35e554d6d5d0408d178981357/api/python/property_value.md#L18)):*
> ```Markdown
> **Signature**: `datacommons.get_property_values(dcids, prop, out=True, value_type=None, limit=datacommons.utils._MAX_LIMIT)`
> 
> **Authentication**: Optional
> ```

Please remove mention of authentication from all the python docs (it had been removed while the PR was in progress earlier..)

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/python/property_value.md, line 61 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MQsp4pG-5viyO4pOp1Y:-MQsp4pG-5viyO4pOp1Z:bywf2t8) ([raw file](https://github.com/datacommonsorg/docsite/blob/d4cfdc24d99840e8e5f1096448d55a278d58d3be/api/python/property_value.md#L61)):*
> ```Markdown
> ```
> 
> ## Example requests and responses
> ```

Not sure if "requests and responses" is appropriate for a python library - perhaps "calls and results" or just simply "Examples" will do.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/property_value.md, line 22 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3TchwAPdnIiMUiGRk:-MQto9Ri8PJ5EZar7kPn:bimdb23) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L22)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Can we update to match REST, wrt glossary references?

As an aside, it would be nice to do another pass through the REST docs after they're all in to standardize how we refer to the glossary.
</blockquote></details>

Updated. 2nd pass through REST = on my to do list!
___
*[api/python/property_value.md, line 76 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MO3n18c0TDv_7WtNckD:-MQtrN0E0Bg0D3NEVQGn:b-d85951) ([raw file](https://github.com/datacommonsorg/docsite/blob/4400f9de93391f1de0125dbd14982b8a313b261c/api/python/property_value.md#L76)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

+1 to using a single block mirroring an interactive python shell (for here and the rest of the python doc updates)
</blockquote></details>

Yep, thanks for the reminder--I completely missed this update! I will go ahead and make those changes.
___
*[api/python/property_value.md, line 16 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MQotQ06E896stV_yWgC:-MQu2XI_CSaMRvxENGzw:bpj6mxs) ([raw file](https://github.com/datacommonsorg/docsite/blob/e68fefeae5fbbd992db7f0343b628c2054901ecf/api/python/property_value.md#L16)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Can we try using  
```python
<method signature here>
```

so that we get some syntax highlighting? I think it would really help readability
</blockquote></details>

I tried the block syntax formatting here, but I'm not sure if that's what you were looking for--let me know what you suggest!
___
*[api/python/property_value.md, line 18 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MQorlXn9DaTlTkXb2Km:-MQto7jZ0R2X9c0PQqTN:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/e68fefeae5fbbd992db7f0343b628c2054901ecf/api/python/property_value.md#L18)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please remove mention of authentication from all the python docs (it had been removed while the PR was in progress earlier..)
</blockquote></details>

Done.
___
*[api/python/property_value.md, line 61 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/107#-MQsp4pG-5viyO4pOp1Y:-MQtqcVOASAqY_Oq28_L:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/e68fefeae5fbbd992db7f0343b628c2054901ecf/api/python/property_value.md#L61)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Not sure if "requests and responses" is appropriate for a python library - perhaps "calls and results" or just simply "Examples" will do.
</blockquote></details>

Done.

**Review by beets — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/107)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @tjann)

**Pull request merged**
