### PR TITLE
Updating documentation for SPARQL REST endpoint

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Final doc updates for the SPARQL REST endpoint. Comments:

- Figuring out SPARQL syntax was a significant pain point for me--I did not and still do not feel like I really understand SPARQL, even after going through the readings linked here. I don't know that this is within scope for this PR, but would it make sense to write a SPARQL tutorial or even more comprehensive instructional material for use within Data Commons?
- I was not able to remove the GET tab from the tabs list in the request samples. Does anyone have any suggestions on how to approach this?

Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
Thanks for doing the research into sparql and the example updates!

Other examples that have came up recently which would be good to add here...

Get GNI observation for countries:

{"sparql": "SELECT ?observation ?place WHERE { ?observation typeOf Observation . ?observation statisticalVariable Amount_EconomicActivity_GrossNationalIncome_PurchasingPowerParity_PerCapita . ?observation observedNodeLocation ?place . ?place typeOf Country .} ORDER BY ASC (?place) LIMIT 10"}

Sample of observations with the unit InternationalDollar:

{ "sparql": "SELECT ?observation WHERE { ?observation typeOf Observation . ?observation unit InternationalDollar } LIMIT 10" }

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112#-:-MO3SlsD4QoRhmAcCf-d:b-4ysq0a)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/query.md, line 13 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3QWJR04ntZhfrY94Q:-MO3QWJR04ntZhfrY94R:be9lj69) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L13)):*
> ```Markdown
> Returns the results of running a graph query on the Data Commons knowledge graph
> using [SPARQL](https://www.w3.org/TR/rdf-sparql-query/).
> ```

We should add the note about only supporting a subset of sparql here
___
*[api/rest/query.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3QBOB43FHT1ejrsyP:-MO3QBOB43FHT1ejrsyQ:buuqz7e) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L20)):*
> ```Markdown
> **Method**: `POST`
> 
> **Authentication**: Optional
> ```

Please remove this line (and references to API key on the page)
___
*[api/rest/query.md, line 34 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3R0f12Muru5DNOj1z:-MO3R0f12Muru5DNOj2-:b-15kyyt) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L34)):*
> ```Markdown
> ### Step 1: Assembling the information you will need
> 
> This endpoint makes it possible to query the Data Commons knowledge graph using SPARQL. SPARQL is a query language developed to retrieve data from websites whose data is formulated using [RDF](https://en.wikipedia.org/wiki/Resource_Description_Framework). It leverages the graph structure innate in the data it queries to return specific information to an end user.
> ```

I think the link to RDF is a distraction (it doesn't get me closer to understanding SPARQL, or the query syntax). Could we remove it?
___
*[api/rest/query.md, line 44 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3RDn39531dP5vkcpw:-MO3RDn39531dP5vkcpx:b-ubcjtf) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L44)):*
> ```
> Here `<query>` denotes the place where the query string will be placed
> ```
Here `<query>` denotes the SPARQL query string.
___
*[api/rest/query.md, line 46 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3QLM-6EtEDJACus4b:-MO3QLM-6EtEDJACus4c:b-dpbid1) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L46)):*
> ```Markdown
> Here `<query>` denotes the place where the query string will be placed. For more information on assembling SPARQL queries, checkout [the Wikipedia page about SPARQL](https://en.wikipedia.org/wiki/SPARQL) and [the W3C specification information](https://www.w3.org/TR/sparql11-query/).
> 
> **NOTES:**
> ```

This note is very important and belongs higher on the page (added a comment above for possible placement)
___
*[api/rest/query.md, line 137 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SQ_gDXzi5JP5h87w:-MO3SQ_gDXzi5JP5h87x:b-g9bw42) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L137)):*
> ```Markdown
> ```
> 
> ### Example 2. Retrieve a list of flash flood events in Prince George's County in Maryland.
> ```

This is a cool example - maybe we should highlight that it queries for both name and dcid

Btw, I wonder if there is another example where there are different names for each event? That threw me off in the example initially.
___
*[api/rest/query.md, line 153 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3RmPY4Ns-oTyS8E8H:-MO3RmPY4Ns-oTyS8E8I:by1sjxx) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L153)):*
> ```Markdown
>                   ?county typeOf County . \
>                   ?county dcid geoId/24033 . \
> 									?county name ?name . \
> ```

Whoops - lots of tabs were added instead of spaces here and in the next line

We can also add LIMIT here to reduce the length of the example.
___
*[api/rest/query.md, line 168 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SJK10FZT7PO-5Gc9:-MO3SJK10FZT7PO-5GcA:b-hxnrzy) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L168)):*
> ```Markdown
> {% endtabs %}
> 
> <script src="/assets/js/tabs.js"></script>
> ```

Not needed anymore since this was added to the default layout
___
*[api/rest/query.md, line 269 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3Sdoi18XltytSKg63:-MO3Sdoi18XltytSKg64:btl85nb) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L269)):*
> ```Markdown
> 	"sparql": "SELECT ?name \
>                 WHERE { \
> 									?biologicalSpecimen typeOf BiologicalSpecimen . \
> ```

A few tabs here as well. It would be nice if the query lined up in the resulting page.

**Review by KilimAnnejaro — COMMENTED** [review]
Added these two :-)

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112#-:-MOUKf09BS-DSZyDC5dl:b-sww1vk)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/query.md, line 13 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3QWJR04ntZhfrY94Q:-MOU5vZF7UBNVORcpi1S:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L13)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We should add the note about only supporting a subset of sparql here
</blockquote></details>

Done.
___
*[api/rest/query.md, line 20 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3QBOB43FHT1ejrsyP:-MOUKzPQ7uqq7Fd-uMW-:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L20)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please remove this line (and references to API key on the page)
</blockquote></details>

Done.
___
*[api/rest/query.md, line 34 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3R0f12Muru5DNOj1z:-MOUL-ov0DZkFSrqbLs7:bb77uci) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L34)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

I think the link to RDF is a distraction (it doesn't get me closer to understanding SPARQL, or the query syntax). Could we remove it?
</blockquote></details>

Yep!
___
*[api/rest/query.md, line 44 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3RDn39531dP5vkcpw:-MOULVXg-jbsUldm6eQC:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L44)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> Here `<query>` denotes the place where the query string will be placed
> ```
Here `<query>` denotes the SPARQL query string.
</blockquote></details>

Done.
___
*[api/rest/query.md, line 46 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3QLM-6EtEDJACus4b:-MOULe4UD9zduZx40Oqr:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L46)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

This note is very important and belongs higher on the page (added a comment above for possible placement)
</blockquote></details>

Done.
___
*[api/rest/query.md, line 168 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SJK10FZT7PO-5Gc9:-MOULz6oAUHZVuJgnBZk:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L168)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Not needed anymore since this was added to the default layout
</blockquote></details>

Done.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/query.md, line 137 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SQ_gDXzi5JP5h87w:-MOUPwf1-0p0Vj7cOC_m:b-67fq8x) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L137)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

This is a cool example - maybe we should highlight that it queries for both name and dcid

Btw, I wonder if there is another example where there are different names for each event? That threw me off in the example initially.
</blockquote></details>

I'm going to remove this example--the flash flood events appear to actually be electrical utilities.
___
*[api/rest/query.md, line 153 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3RmPY4Ns-oTyS8E8H:-MOUQCGOD1_V6QrYMdYc:bribihm) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L153)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Whoops - lots of tabs were added instead of spaces here and in the next line

We can also add LIMIT here to reduce the length of the example.
</blockquote></details>

As above.
___
*[api/rest/query.md, line 269 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3Sdoi18XltytSKg63:-MOUQDtmEcWBRzpR9a6R:bt2vr1b) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L269)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

A few tabs here as well. It would be nice if the query lined up in the resulting page.
</blockquote></details>

Fixed.

**Review by beets — CHANGES_REQUESTED** [review]
Thanks for the update! Just a few formatting nitpicks.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112#-:-MQIyKWw0Q2XogDc-5F2:b-pxvk5n)* status: all files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/query.md, line 137 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SQ_gDXzi5JP5h87w:-MQIxEVd-aLFZzrjLlmn:b-vzrg1o) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L137)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I'm going to remove this example--the flash flood events appear to actually be electrical utilities.
</blockquote></details>

ouch! ok sounds good
___
*[api/rest/query.md, line 168 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SJK10FZT7PO-5Gc9:-MQIxNIy5QAchE6mGwpa:bmc6b70) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L168)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still here.. maybe you forgot to commit the change?
___
*[api/rest/query.md, line 269 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3Sdoi18XltytSKg63:-MQIxvQ85MnrPTfhNFoh:bu8spc3) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L269)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Could we format the query as in the first example?
___
*[api/rest/query.md, line 280 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MQIxkfeA6vugUY-YOet:-MQIxkfeA6vugUY-YOeu:b-iyvanz) ([raw file](https://github.com/datacommonsorg/docsite/blob/f449f200c40c81deedd7ba622e4d059f51a55d97/api/rest/query.md#L280)):*
> ```Markdown
>   --url https://api.datacommons.org/query \
>   --header 'content-type: application/json' \
>   --data '{"sparql": "SELECT ?observation ?place WHERE { ?observation typeOf Observation . ?observation statisticalVariable Amount_EconomicActivity_GrossNationalIncome_PurchasingPowerParity_PerCapita . ?observation observedNodeLocation ?place . ?place typeOf Country .} ORDER BY ASC (?place) LIMIT 10"}'
> ```

It would be helpful to see the query string formatted as above (separate lines, indented, etc)
___
*[api/rest/query.md, line 536 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MQIyFwMBRthQKG9Y0MG:-MQIyFwN2PimKXvqb1h9:b4xluow) ([raw file](https://github.com/datacommonsorg/docsite/blob/f449f200c40c81deedd7ba622e4d059f51a55d97/api/rest/query.md#L536)):*
> ```Markdown
>   --header 'content-type: application/json' \
>   --data '{
> 	"sparql": "SELECT DISTINCT ?LifeExpectancy \
> ```

please use spaces instead of tabs

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112)* status: all files reviewed, 5 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/query.md, line 168 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SJK10FZT7PO-5Gc9:-MQV0_PT7VdhZhYo025a:b-wcsah5) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L168)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

It's still here.. maybe you forgot to commit the change?
</blockquote></details>

Just as an FYI: I tried removing the script tag just now, and when I try to do so, I am auto-scrolled to the top of the page when I click on a tab (instead of being transferred to that tab's view). So I feel like these script tags might still be needed? Not sure--thoughts appreciated!
___
*[api/rest/query.md, line 269 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3Sdoi18XltytSKg63:-MQV7nLe-uH8u5pZUgTO:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L269)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Could we format the query as in the first example?
</blockquote></details>

Done.
___
*[api/rest/query.md, line 280 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MQIxkfeA6vugUY-YOet:-MQV6vQPDegKOyRswOV4:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/f449f200c40c81deedd7ba622e4d059f51a55d97/api/rest/query.md#L280)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

It would be helpful to see the query string formatted as above (separate lines, indented, etc)
</blockquote></details>

Done.
___
*[api/rest/query.md, line 536 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MQIyFwMBRthQKG9Y0MG:-MQV8AFyBew5-83FonY6:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/f449f200c40c81deedd7ba622e4d059f51a55d97/api/rest/query.md#L536)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

please use spaces instead of tabs
</blockquote></details>

Done.

**Review by beets — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/112)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @beets and @tjann)

___
*[api/rest/query.md, line 168 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/112#-MO3SJK10FZT7PO-5Gc9:-MQoqyknAVbiEYozaScZ:b-sqrb80) ([raw file](https://github.com/datacommonsorg/docsite/blob/5751661723d48ae633a59a40d22778aa8e4263db/api/rest/query.md#L168)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Just as an FYI: I tried removing the script tag just now, and when I try to do so, I am auto-scrolled to the top of the page when I click on a tab (instead of being transferred to that tab's view). So I feel like these script tags might still be needed? Not sure--thoughts appreciated!
</blockquote></details>

How odd. We can fix that up later then.

**Pull request merged**
