### PR TITLE
Rename Graph Browser to Knowledge Graph

### PR DESCRIPTION
**Pull request by juliawu**
Renames the "Graph Browser" to "Knowledge Graph Browser" to make it more clear for users the browsers is for viewing nodes & edges, not viewing charts.

This change pairs with [this renaming PR on the website repo](https://github.com/datacommonsorg/website/pull/4153).

Sample screenshots of the changes:

Screenshot 2024-04-29 at 1 02 12 PM
Screenshot 2024-04-29 at 1 02 36 PM

### CODE REVIEW

**Comment by juliawu** [comment]
@kmoscoe FYI

**Comment by juliawu** [comment]
Per conversation in https://github.com/datacommonsorg/website/pull/4153 with @miss-o-soup, switched from "Knowledge Graph Browser" to "Knowledge Graph". Updated screenshots and PR title to reflect this change.

**Comment by dwnoble** [comment]
Adding @kmoscoe to help review docsite changes

**Review by dwnoble — COMMENTED** [review]
Thank you!

One more place:

https://github.com/datacommonsorg/docsite/blob/4d5bf511e6c6f9e143b8b94aa51f1815cd93ccaa/README.md?plain=1#L20

Also- looks like we have some inconsistencies in calling the tool "Knowledge Graph" vs "knowledge graph" - @miss-o-soup any preferences here?

https://screenshot.googleplex.com/9ugGMNnoTeP3wem
https://screenshot.googleplex.com/7z2o2SZmXVQMsH5

**Comment by kmoscoe** [comment]
It might be worthwhile doing a general find and replace in all the files in the docsite. Don't worry about custom DC or other docs in various repos. I'll change them as I migrate them.

**Comment by juliawu** [comment]
> Thank you!
> 
> One more place:
> 
> https://github.com/datacommonsorg/docsite/blob/4d5bf511e6c6f9e143b8b94aa51f1815cd93ccaa/README.md?plain=1#L20
> 
> Also- looks like we have some inconsistencies in calling the tool "Knowledge Graph" vs "knowledge graph" - @miss-o-soup any preferences here?
> 
> https://screenshot.googleplex.com/9ugGMNnoTeP3wem https://screenshot.googleplex.com/7z2o2SZmXVQMsH5

Thanks! Updated the README. Differing to @kmoscoe and @miss-o-soup on when to capitalize.

**Comment by juliawu** [comment]
> It might be worthwhile doing a general find and replace in all the files in the docsite. Don't worry about custom DC or other docs in various repos. I'll change them as I migrate them.

PR was generated by a find and replace for "graph browser". Following @dwnoble's comment, also searched all files for "browser". The only file I skipped updating was [this old blog post](https://github.com/datacommonsorg/docsite/blob/master/_posts/2021-06-01-updates.md?plain=1#L15-L17) to preserve the blog post timeline.

**Review by dwnoble — APPROVED** [review]
Thank you!

Some other potential places to update:

https://screenshot.googleplex.com/7j6MTpVNnsE9ewg
https://github.com/datacommonsorg/website/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L15
https://github.com/datacommonsorg/website/blob/master/.github/ISSUE_TEMPLATE/feedback.md?plain=1#L15

**Comment by kmoscoe** [comment]
Capitalize the Knowledge Graph here since you're referring to it as a tool.

**Comment by juliawu** [comment]
> Capitalize the Knowledge Graph here since you're referring to it as a tool.

Great, added capitalization whenever we referred to the Knowledge Graph as a tool.

**Comment by juliawu** [comment]
> Thank you!
> 
> Some other potential places to update:
> 
> https://screenshot.googleplex.com/7j6MTpVNnsE9ewg https://github.com/datacommonsorg/website/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L15 https://github.com/datacommonsorg/website/blob/master/.github/ISSUE_TEMPLATE/feedback.md?plain=1#L15

Thanks! I'll update the screenshot in the website repo PR, that page isn't on our docsite.

As for the issue templates, I believe "Browser:" refers to the internet browser the user observed the issue on (chrome, firefox, etc), not our knowledge graph browser.

**Comment by miss-o-soup** [comment]
I think Kara replied already, I would defer to her... But yes, it is my understanding that we capitalize product name/features "Knowledge Graph" in this case since it is the tool.

**Pull request merged**
