### PR TITLE
Rest property label content

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Polished first draft on documenting the REST property label endpoint.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96)

### CODE REVIEW

**Comment by KilimAnnejaro** [comment]
Note: feedback on this one's fiddles appreciated!

**Review by beets — CHANGES_REQUESTED** [review]
Thanks and sorry for the late review. Comments mostly center around applying changes we made in #95 here for consistency. Fiddle looks good!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96#-:-MO3C2iM-K8ogw0JDLay:b-h9iysj)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/property_label.md, line 27 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3AIFy6QtIa_n6IKP8:-MO3AIFy6QtIa_n6IKP9:btqr19k) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L27)):*
> ```Markdown
> **Optional Arguments**:
> 
> *   `key`: Your API key.
> ```

Please remove references to API key (applies to all endpoints) -- we've removed documentation on how to create the key, so removing the argument reduces complexity.
___
*[api/rest/property_label.md, line 57 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3AfVN9bRuDcT1pfSv:-MO3AfVN9bRuDcT1pfSw:bspy4xe) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L57)):*
> ```Markdown
> ```json
> {
>     "dcid": {
> ```

Same as before, please use angle brackets to denote when it's a reference.
___
*[api/rest/property_label.md, line 72 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3ApFrE7DuJrXmLNFH:-MO3ApFrE7DuJrXmLNFI:b-h0m0qc) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L72)):*
> ```Markdown
> 
> For each node, `inLabels` contains labels directed towards the node while
> `outLabels` contains labels directed away from the node.
> ```

Should we add a similar note here about directionality from #95?
___
*[api/rest/property_label.md, line 117 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3B3ih5Bboytn_IgT_:-MO3B3ih5Bboytn_IgTa:b-8mdyrc) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L117)):*
> ```Markdown
> </div>
> 
> #### Response
> ```

Like in #95. should we include both raw and parsed/prettified responses? (applies to the next example as well)
___
*[assets/js/tabs.js, line 58 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3BJCY1HLJzKwx0aI-:-MO3BJCY1HLJzKwx0aI0:bm3s7ks) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/assets/js/tabs.js#L58)):*
> ```JavaScript
>     }, false);
>   });
> }); 
> ```

Please revert this whitespace change

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/property_label.md, line 27 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3AIFy6QtIa_n6IKP8:-MO4phIY9t40KdAKllX7:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L27)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please remove references to API key (applies to all endpoints) -- we've removed documentation on how to create the key, so removing the argument reduces complexity.
</blockquote></details>

Done.
___
*[api/rest/property_label.md, line 57 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3AfVN9bRuDcT1pfSv:-MO4pkWSCGG_zGFCvzUl:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L57)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Same as before, please use angle brackets to denote when it's a reference.
</blockquote></details>

Done.
___
*[assets/js/tabs.js, line 58 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3BJCY1HLJzKwx0aI-:-MO4qA8k6HWxJLdBiNlm:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/assets/js/tabs.js#L58)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please revert this whitespace change
</blockquote></details>

Done.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/property_label.md, line 72 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3ApFrE7DuJrXmLNFH:-MO4swGp9DuRSYqAGQ3I:bl2im9b) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L72)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Should we add a similar note here about directionality from #95?
</blockquote></details>

I pointed the reader to the documentation we've added to the property value endpoint. Would you like me to more explicitly copy that documentation to this page?
___
*[api/rest/property_label.md, line 117 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3B3ih5Bboytn_IgT_:-MO4rUv9C0UVM5h9Cga2:b7s19m8) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L117)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Like in #95. should we include both raw and parsed/prettified responses? (applies to the next example as well)
</blockquote></details>

Great idea! I've incorporated that.

**Review by beets — CHANGES_REQUESTED** [review]
thanks for the update! one small request below

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96#-:-MO8pw_dBMajsBEZb1RW:b-n0pmgj)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/property_label.md, line 57 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3AfVN9bRuDcT1pfSv:-MO8pj297PgftlOvfStR:b-r6t8dx) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L57)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you do the same for both "label" below?
___
*[api/rest/property_label.md, line 72 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3ApFrE7DuJrXmLNFH:-MO8ppTd0iTP74u68oL2:bv3frr3) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L72)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I pointed the reader to the documentation we've added to the property value endpoint. Would you like me to more explicitly copy that documentation to this page?
</blockquote></details>

That could belong in the glossary. In the meantime, this reference works.

**Review by tjann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/property_label.md, line 23 at r4](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO8vclzCImX6e_UAcOA:-MO8vclzCImX6e_UAcOB:b-7tq076) ([raw file](https://github.com/datacommonsorg/docsite/blob/3a0f4ef6e28061eba220df103421d3c8ced2e2a6/api/rest/property_label.md#L23)):*
> ```Markdown
> **Required Arguments**:
> 
> *   `dcids`: A list of nodes to query, identified by their `DCIDs`.
> ```

can we do `dcid`s with a link to glossary or browser (until glossary is finalized)?

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/property_label.md, line 57 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3AfVN9bRuDcT1pfSv:-MO9aKWM9EKADaR4Spii:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L57)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Could you do the same for both "label" below?
</blockquote></details>

Done.
___
*[api/rest/property_label.md, line 72 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO3ApFrE7DuJrXmLNFH:-MO9aORDAeZMuyaCF7hA:b32v57) ([raw file](https://github.com/datacommonsorg/docsite/blob/b9e3b9f13d8ca943a8aa152174948f351dab97ce/api/rest/property_label.md#L72)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

That could belong in the glossary. In the meantime, this reference works.
</blockquote></details>

+1
___
*[api/rest/property_label.md, line 23 at r4](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO8vclzCImX6e_UAcOA:-MO9aDq405x6NVjBgwfF:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/3a0f4ef6e28061eba220df103421d3c8ced2e2a6/api/rest/property_label.md#L23)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

can we do `dcid`s with a link to glossary or browser (until glossary is finalized)?
</blockquote></details>

Done.

**Review by tjann — COMMENTED** [review]
Thanks Annie! This is a huge improvement from our current page!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96#-:-MOcS-XXEFcD3ewKyHas:b-xsy5ml)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/property_label.md, line 23 at r4](https://reviewable.io/reviews/datacommonsorg/docsite/96#-MO8vclzCImX6e_UAcOA:-MOcN_Rr54WGLHsgaMWE:bhse3b9) ([raw file](https://github.com/datacommonsorg/docsite/blob/3a0f4ef6e28061eba220df103421d3c8ced2e2a6/api/rest/property_label.md#L23)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant like this: [`dcid`](https://datacommons.org/browser/dcid)s

```
[`dcid`](https://datacommons.org/browser/dcid)s
```

Now that the glossary is published, maybe we can do 

```
[DCID](https://docs.datacommons.org/glossary.html#DCID)s
```

Except that the glossary doesn't actually allow us to link directly to an vocab entry :( maybe a next feature request?

**Review by beets — CHANGES_REQUESTED** [review]
Thanks for the update! Could you please resolve the remaining comments? Then we're good to go on this.

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96#-:-MQInG50CA1rmbQhsa1z:bwkysbq)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @beets and @KilimAnnejaro)

**Review by KilimAnnejaro — COMMENTED** [review]
@beets I think I resolved all the remaining comments? Let me know what you think!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96#-:-MQKitFj0qsxNGS2zC84:bpxgfq3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

**Review by beets — APPROVED** [review]
great thanks! merging

> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/96#-:-MQNtmNvDYxLFRfdQCS6:b-qboc2z)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

**Review by tjann — APPROVED** [review]

**Pull request merged**
