### PR TITLE
Pandas time series polished first draft

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
Polished first draft for the Pandas time series doc.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
sorry for the delayed review. thanks for adding the new examples!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118#-:-MSWB-mV535Q7WBZB0WT:b-lj65q6)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/pandas/time_series.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWALKr45Wv9IxvJPcC:-MSWALKr45Wv9IxvJPcD:b-iivsv2) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L9)):*
> ```Markdown
> ---
> 
> # Get Time Series for a Place
> ```

Get -> Retrieve for consistency? Applies to the other pandas APIs too
___
*[api/pandas/time_series.md, line 18 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAGdO1OAzcKCem6U9:-MSWAGdO1OAzcKCem6UA:bbo4aja) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L18)):*
> ```Markdown
> ## General information about this method
> 
> **Signature**: `datacommons_pandas.build_time_series(place, stat_var, measurement_method=None,observation_period=None, unit=None, scaling_factor=None)`
> ```

Could we use ```python here as well, to get syntax highlighting (applies to the other pandas APIs too)
___
*[api/pandas/time_series.md, line 31 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAZ1XAjCUv9n8fZR0:-MSWAZ1XAjCUv9n8fZR1:bjzk2g8) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L31)):*
> ```Markdown
> Going into more detail on how to assemble the values for the required arguments:
> 
> - [`place`](/glossary.html): For this parameter, you will need to specify the DCID (the unique ID assigned by Data Commons to each node in the graph) of the place you are interested in.
> ```

the glossary links might need to be updated?
___
*[api/pandas/time_series.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAV41B6StSC_uLg1n:-MSWAV41B6StSC_uLg1o:b-jnaaaa) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L36)):*
> ```Markdown
> In addition to these required properties, this endpoint also allows for other, optional arguments. Here are helpful arguments in regular use by Data Commons developers:
> 
> - [`measurement_method`](/glossary.html): You can specify this argument as out to indicate that you desire the response to only include nodes which are supercategories of the specified DCIDs, or in to only return nodes that are subcategories of the specified DCIDs. (For example, South America is a supercategory of Argentina, which in turn is a supercategory of Buenos Aires, as illustrated in Figure 1.)
> ```

Please update the list here (the descriptions are for other properties)

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

___
*[api/pandas/time_series.md, line 9 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWALKr45Wv9IxvJPcC:-MSpNudGCeP--mPOTCFd:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Get -> Retrieve for consistency? Applies to the other pandas APIs too
</blockquote></details>

Done.
___
*[api/pandas/time_series.md, line 18 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAGdO1OAzcKCem6U9:-MSpNzlr2WGPlRpA1zQu:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L18)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Could we use ```python here as well, to get syntax highlighting (applies to the other pandas APIs too)
</blockquote></details>

Done.
___
*[api/pandas/time_series.md, line 31 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAZ1XAjCUv9n8fZR0:-MSpO9vF9mcofw-VaycO:b-kd6deb) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L31)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

the glossary links might need to be updated?
</blockquote></details>

This works as expected for me on my local build. Is there a need for an absolute address?
___
*[api/pandas/time_series.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAV41B6StSC_uLg1n:-MSpOsKlCfLRw4h3dmvX:bxhg0dz) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L36)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please update the list here (the descriptions are for other properties)
</blockquote></details>

Whoops, that is a mistake--thanks for pointing it out! Also wanted to let you know that per one of our discussions, I added additional language towards the end of this section pointing interested readers to the glossary. If it is preferred, I can add that link at the end of each term too--let me know what you think!

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/pandas/time_series.md, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MT6uC8e9-Ysl4goH8gt:-MT6uC8e9-Ysl4goH8gu:bbnixhf) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L14)):*
> ```Markdown
> [`stat_var`](https://datacommons.org/browser/StatisticalVariable) satisfying any optional parameters.
> 
> See the [full list of `StatisticalVariable` classes](/statistical_variables.html).
> ```

These aren't classes - just variables. Could we move this to the end of line 26? Seems like a more natural spot for it.
___
*[api/pandas/time_series.md, line 18 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAGdO1OAzcKCem6U9:-MT6uKXt4NbeEB5XkbrU:b489tix) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L18)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe you forgot to push the commit?
___
*[api/pandas/time_series.md, line 31 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAZ1XAjCUv9n8fZR0:-MT6uozPElAd9mo9sRXZ:b-ddttdd) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L31)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

This works as expected for me on my local build. Is there a need for an absolute address?
</blockquote></details>

Hm, I suppose not. I encountered a broken link somewhere - will take a better note when I see it again.
___
*[api/pandas/time_series.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAV41B6StSC_uLg1n:-MT6v-en5G7v94uEFbzE:b4m8nkf) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L36)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Whoops, that is a mistake--thanks for pointing it out! Also wanted to let you know that per one of our discussions, I added additional language towards the end of this section pointing interested readers to the glossary. If it is preferred, I can add that link at the end of each term too--let me know what you think!
</blockquote></details>

Yes - I like what you have at the end of the section - could you apply this to the rest of the docs as well? Thanks!

**Review by beets — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/pandas/time_series.md, line 18 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAGdO1OAzcKCem6U9:-MT6vfmG39u3aEE40npF:bnpfovs) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L18)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Maybe you forgot to push the commit?
</blockquote></details>

My bad - I saw a stale diff :(

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/pandas/time_series.md, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MT6uC8e9-Ysl4goH8gt:-MT8srcQ69voFs2bUycy:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L14)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

These aren't classes - just variables. Could we move this to the end of line 26? Seems like a more natural spot for it.
</blockquote></details>

Done.
___
*[api/pandas/time_series.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/118#-MSWAV41B6StSC_uLg1n:-MT8stdQ-Ykg6FWr9mDj:b-9nw43w) ([raw file](https://github.com/datacommonsorg/docsite/blob/103e40b91e89ba2d6327edb0ef4728261393f073/api/pandas/time_series.md#L36)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Yes - I like what you have at the end of the section - could you apply this to the rest of the docs as well? Thanks!
</blockquote></details>

Yep, we can do that!

**Review by beets — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/118)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @tjann)

**Pull request merged**
