### PR TITLE
Fix broken links to relation expressions section.

### PR DESCRIPTION
**Pull request by kmoscoe**

### CODE REVIEW

**Review by juliawu — APPROVED** [review]

**Comment by beets** [comment]
The link is working for me without the change: https://docs.datacommons.org/api/rest/v2#relation-expressions
If it doesn't work, there are a few other places to update.

**Comment by kmoscoe** [comment]
Hmm, that's odd. When I try to link to it, I get 404s/

**Comment by kmoscoe** [comment]
https://screenshot.googleplex.com/6qMkkJzudFcSTPE

The funny thing is that when I tried using index.html, that didn't work
either. Carolyn, is there something configured differently for these files?

**Comment by beets** [comment]
This link works for me:
https://docs.datacommons.org/api/rest/v2#relation-expressions

**Pull request closed without merging**
