### PR TITLE
Python stat-all endpoint

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
As with the REST version of this endpoint, I think it makes sense to keep this one simple for success. I made a few changes per the style guide, but mostly I just incorporated the work we discussed on https://github.com/datacommonsorg/docsite/pull/98/files.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)

### CODE REVIEW

**Review by tjann — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/stat_all.md, line 14 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3pSQI6HQI-_XIBSCC:-MO3pSQI6HQI-_XIBSCD:bkxzdj7) ([raw file](https://github.com/datacommonsorg/docsite/blob/32ae12a64df1dc6df505b65584ef68d9aa4a7ffd/api/python/stat_all.md#L14)):*
> ```Markdown
> 
> Returns a nested `dict` of all time series for [`places`](https://datacommons.org/browser/Place) and [`stat_vars`](https://datacommons.org/browser/StatisticalVariable).
> Note that in Data Commons, a Statistical Variable is any type of statistical metric that can be measured at a place and
> ```

nit: any statistical metric
___
*[api/python/stat_all.md, line 19 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3pb1r9Hjo2X1s3DeO:-MO3pb1r9Hjo2X1s3DeP:b-vbhmgg) ([raw file](https://github.com/datacommonsorg/docsite/blob/32ae12a64df1dc6df505b65584ef68d9aa4a7ffd/api/python/stat_all.md#L19)):*
> ```Markdown
> **Arguments**
> 
> - `places (Iterable of str)`: The `dcids` of the [`Places`](https://datacommons.org/browser/Place) to query for. (Here DCID stands for Data Commons ID, the unique identifier assigned to all entities in Data Commons.)
> ```

Can we do
```
The DCIDs of the [`Place`](https://datacommons.org/browser/Place)s
```
?

For the first change, it's bc I think it makes sense to just use DCID instead of `dcid` when we aren't linking to browser pages or referring to function parameters.

For the second change, I don't want people to e.g. think "Places" is ID-accurate, especially when we link to a browser page. Could you apply this suggestion to the rest of this and other PRs? TL;DR is if you `code-face` a DCID, make any pluralization after the code-face.
___
*[api/python/stat_all.md, line 35 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3rwVU7NZbce0wbVGN:-MO3rwVU7NZbce0wbVGO:b2ta970) ([raw file](https://github.com/datacommonsorg/docsite/blob/32ae12a64df1dc6df505b65584ef68d9aa4a7ffd/api/python/stat_all.md#L35)):*
> ```Markdown
> - `val`: a dict with dates keyed to statistical values.
> - `importName`: the dataset source name for the observations.
> - `provenanceDomain`: the [Provenance](https://datacommons.org/browser/Provenance) domain of the observations.
> ```

domain URL? I'm not sure
___
*[api/python/stat_all.md, line 39 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3slxd08YXAqqJIH3K:-MO3slxd08YXAqqJIH3L:beacjoo) ([raw file](https://github.com/datacommonsorg/docsite/blob/32ae12a64df1dc6df505b65584ef68d9aa4a7ffd/api/python/stat_all.md#L39)):*
> ```Markdown
> - `observationPeriod`: the [`observationPeriod`](https://datacommons.org/browser/observationPeriod) of the observations, if it exists.
> - `unit`: the [`unit`](https://datacommons.org/browser/unit) of the observations, if it exists.
> - `scalingFactor`: the [`scalingFactor`](https://datacommons.org/browser/scalingFactor) of the observations, if it exists.
> ```

High level proposal, I ran this by cyin-- once we republish the glossary, can we make those definitions the gold standard, and replace these browser links with links to the glossary?

Other candidates that could go into the glossary include explaining in/out for property-values, and anything else that is repeated across python/rest, or even within rest/python. 
___
*[api/python/stat_all.md, line 52 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3tHNZ5gqMlxXWo74I:-MO3tHNZ5gqMlxXWo74J:b-k950u2) ([raw file](https://github.com/datacommonsorg/docsite/blob/32ae12a64df1dc6df505b65584ef68d9aa4a7ffd/api/python/stat_all.md#L52)):*
> ```Markdown
> ```python
> >>> import datacommons as dc
> >>> dc.get_stat_all(["geoId/05"], ["Count_Person", "Count_Person_Male"])
> ```

Could you add another example with multiple places?

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/stat_all.md, line 19 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3pb1r9Hjo2X1s3DeO:-MOURdcL-41nRnOsWC2c:b-1h9dbt) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L19)):*
> The DCIDs of the [`Place`](https://datacommons.org/browser/Place)s
Yep, this is a great comment! I think I put something about plurals in one of our other discussions--we want to not pluralize objects in code face as such; instead we'd like to pluralize these objects as `Place` objects instead. So I updated this line to reflect that--let me know what you think!
___
*[api/python/stat_all.md, line 35 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3rwVU7NZbce0wbVGN:-MOUTpLtBrspTXgzyV96:b-77b7a4) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L35)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

domain URL? I'm not sure
</blockquote></details>

Seems reasonable.
___
*[api/python/stat_all.md, line 39 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3slxd08YXAqqJIH3K:-MOUT1qr8WI2cFC3uI1m:b-x8uxov) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L39)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

High level proposal, I ran this by cyin-- once we republish the glossary, can we make those definitions the gold standard, and replace these browser links with links to the glossary?

Other candidates that could go into the glossary include explaining in/out for property-values, and anything else that is repeated across python/rest, or even within rest/python. 
</blockquote></details>

YES we should and will do that!
___
*[api/python/stat_all.md, line 52 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3tHNZ5gqMlxXWo74I:-MOUV2ZB1BGBjMXUnxiI:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L52)):*
<details><summary><i>Previously, tjann (TJann) wrote…</i></summary><blockquote>

Could you add another example with multiple places?
</blockquote></details>

Done.

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/stat_all.md, line 39 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3slxd08YXAqqJIH3K:-MQsoOJ90AwybTSu9Qw3:b-p1goqy) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L39)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

YES we should and will do that!
</blockquote></details>

Now that the glossary is out - we can point there instead of browser :)
___
*[api/python/stat_all.md, line 45 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MQsos9mAAvlmy3cG1qb:-MQsos9mAAvlmy3cG1qc:b148edk) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L45)):*
> ```Markdown
> Be sure to initialize the library. Check the [Python library setup guide](/api/python/) for more details.
> 
> ## Examples
> ```

please update to match other PRs (we should decide on one) - this has a separate heading for each example:
https://github.com/datacommonsorg/docsite/pull/107/files
___
*[api/python/stat_all.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MQsoWyrBA-lQJnlFK9g:-MQsoWyrBA-lQJnlFK9h:bk4c78c) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L47)):*
> ```Markdown
> ## Examples
> 
> This example retrieves the [population](https://datacommons.org/browser/Count_Person) and the [male population](https://datacommons.org/browser/Count_Person_Male) in [Arkansas](https://datacommons.org/browser/geoId/05) and
> ```

perhaps qualify the first population with "total population"
___
*[api/python/stat_all.md, line 52 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3tHNZ5gqMlxXWo74I:-MQspIgPED7FIg3aZU7w:b-t212nw) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L52)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe you forgot to push the added example?

**Review by KilimAnnejaro — COMMENTED** [review]
I will circle back to this review--needs more changes

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113#-:-MQuK2qB6R-soAP0D0x5:b-iqgcmt)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/stat_all.md, line 39 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3slxd08YXAqqJIH3K:-MQyx1l-3iFNH-0K4_Lu:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L39)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Now that the glossary is out - we can point there instead of browser :)
</blockquote></details>

Done.
___
*[api/python/stat_all.md, line 45 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MQsos9mAAvlmy3cG1qb:-MQywx2E8heyclLod1do:bg932hn) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L45)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

please update to match other PRs (we should decide on one) - this has a separate heading for each example:
https://github.com/datacommonsorg/docsite/pull/107/files
</blockquote></details>

Overhauled styling on this PR to match the others--let me know what you think!
___
*[api/python/stat_all.md, line 47 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MQsoWyrBA-lQJnlFK9g:-MQyrchg0QeZnH_Dv3yj:b-oz8tym) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L47)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

perhaps qualify the first population with "total population"
</blockquote></details>

Good call.
___
*[api/python/stat_all.md, line 52 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3tHNZ5gqMlxXWo74I:-MQyq2Gs6aspQLpYVFeI:b-vkjtat) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L52)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Maybe you forgot to push the added example?
</blockquote></details>

It's showing up in https://github.com/datacommonsorg/docsite/pull/113/files as the comparison of the populations of doctoral degree holders in Minnesota and Wisconsin. Perhaps I am missing something?

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/python/stat_all.md, line 52 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MO3tHNZ5gqMlxXWo74I:-MRS5Fq3C1gWZHkv_BCh:b2h78dz) ([raw file](https://github.com/datacommonsorg/docsite/blob/1454dbb1415c1e3efc863d4aca5109ed7fee8070/api/python/stat_all.md#L52)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

It's showing up in https://github.com/datacommonsorg/docsite/pull/113/files as the comparison of the populations of doctoral degree holders in Minnesota and Wisconsin. Perhaps I am missing something?
</blockquote></details>

Gotcha - I missed that.
___
*[api/python/stat_all.md, line 9 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MRS4sbH4MiZT5g1seVR:-MRS4sbH4MiZT5g1seVS:b-kkf2tf) ([raw file](https://github.com/datacommonsorg/docsite/blob/b5ec166920ffe63dbfa543d1c70ef0c6e26b8d05/api/python/stat_all.md#L9)):*
> ```Markdown
> ---
> 
> # Get a collection of statistical data for multiple places
> ```

Should this be "Retrieve" as well to match the other pages?
___
*[api/python/stat_all.md, line 17 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MRS4xl0BXn3mYkPVtpH:-MRS4xl0BXn3mYkPVtpI:buhvzue) ([raw file](https://github.com/datacommonsorg/docsite/blob/b5ec166920ffe63dbfa543d1c70ef0c6e26b8d05/api/python/stat_all.md#L17)):*
> ```Markdown
> ## General information about this method
> 
> **Signature**: `datacommons.get_stat_all(places, stat_vars)`
> ```

Can we update to use ```python here, so there is syntax highlighting?

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/113)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/stat_all.md, line 9 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MRS4sbH4MiZT5g1seVR:-MS19y5k73d2GRYktGqv:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b5ec166920ffe63dbfa543d1c70ef0c6e26b8d05/api/python/stat_all.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Should this be "Retrieve" as well to match the other pages?
</blockquote></details>

Done.
___
*[api/python/stat_all.md, line 17 at r3](https://reviewable.io/reviews/datacommonsorg/docsite/113#-MRS4xl0BXn3mYkPVtpH:-MS1ANpx83XWywIUEURR:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/b5ec166920ffe63dbfa543d1c70ef0c6e26b8d05/api/python/stat_all.md#L17)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Can we update to use ```python here, so there is syntax highlighting?
</blockquote></details>

Done.

**Review by beets — APPROVED** [review]
thx for the updates!

**Pull request merged**
