### PR TITLE
Python property label doc update

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
PR for updating the property label Python documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/108)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/108)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/property_label.md, line 17 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3MSOcAMVZQMyrETCW:-MO3MSOd8VoHkG-1lfgZ:b-wcf7qs) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L17)):*
> ```Markdown
> **Signature**: `datacommons.get_property_labels(dcids, out=True)`
> 
> **Authentication**: Optional
> ```

Please remove any references to auth as you see them
___
*[api/python/property_label.md, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Mnpu8Y8-81wQFk2v:-MO3Mnpu8Y8-81wQFk2w:bfe4rzw) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L33)):*
> ```Markdown
>  - `dcids`: Data Commons uniquely identifies nodes by assigning them DCIDs, or Data Commons IDs. Your query will need to specify the DCIDs for the nodes of interest.
> 
> In addition to these required properties, this endpoint also allows for the additional, optional argument `out`. This is a boolean value that refers to the orientation, or direction, of the edge. You can specify this argument as `True` to indicate that you desire the response to only include nodes with the value of the property equivalent to one or more of the specified `DCIDs`, or `False` to only return nodes equivalent to one or more of the values of the properties of the specified `DCIDs`. (To visualize this, Figure 1 illustrates the directions for the property `containedInPlace` of the node for Argentina.)
> ```

Even though this only has one optional argument, it would help readability to also include a bullet (like for the required list above).

Also, should we include Figure 1 here? Or we can include this in the glossary and point there for a deeper explanation?
___
*[api/python/property_label.md, line 39 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3NAOE-OHyZWG0uHv-:-MO3NAOE-OHyZWG0uHv0:bibsl5e) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L39)):*
> ```Markdown
> The method's return value will always be a `dict` in the following form:
> 
> ```json
> ```

We should use python formatting for this file (here and below)
___
*[api/python/property_label.md, line 53 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Nj1t4o-hGpSqMgmK:-MO3Nj1t4o-hGpSqMgmL:b-3n4jai) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L53)):*
Should we keep the interactive python shell style for the examples? Like what we had before (and we should keep the import statement so calling "dc" makes sense:

>>> import datacommons as dc
>>> dc.get_property_labels
[result]
___
*[api/python/property_label.md, line 58 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3NTBh5tHt6FyEn15-:-MO3NTBh5tHt6FyEn150:b-xmjiwx) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L58)):*
> ```Markdown
> #### Response
> 
> ##### Raw
> ```

The raw vs parsed distinction isn't required for python api's, since we always return parsed results
___
*[api/python/property_label.md, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3ODaR5X2TWZUZfmIe:-MO3ODaR5X2TWZUZfmIf:babczdq) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L114)):*
> ```
> If there is no value
> ```
If there are no nodes

Also, we should update the example since those are actually valid nodes.

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/108)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @KilimAnnejaro and @tjann)

___
*[api/python/property_label.md, line 53 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Nj1t4o-hGpSqMgmK:-MO3P-Ml2PLR-ceyu3S2:b-wlbdx1) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L53)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Should we keep the interactive python shell style for the examples? Like what we had before (and we should keep the import statement so calling "dc" makes sense:

>>> import datacommons as dc
>>> dc.get_property_labels
[result]
</blockquote></details>

We can also update the example to be:

import datacommons
datacommons.get_property_labels(...)

to match the function signature used above.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/108)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/property_label.md, line 17 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3MSOcAMVZQMyrETCW:-MOS1_Ai1D4Xk3OHw3Hy:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L17)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Please remove any references to auth as you see them
</blockquote></details>

Done.
___
*[api/python/property_label.md, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Mnpu8Y8-81wQFk2v:-MOS3UAB8Gefp7J7NepA:b-1oq2ap) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L33)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Even though this only has one optional argument, it would help readability to also include a bullet (like for the required list above).

Also, should we include Figure 1 here? Or we can include this in the glossary and point there for a deeper explanation?
</blockquote></details>

I broke this up into a bullet point, as suggested.
Eventually I would prefer for Figure 1 to be in the glossary, but until that PR gets approved, I'm duplicating definitions and figures to every location where they are needed. So I went ahead and added Figure 1 here--let me know what you think!
___
*[api/python/property_label.md, line 39 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3NAOE-OHyZWG0uHv-:-MOS8TDz-F7FS0ZC_JAk:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L39)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We should use python formatting for this file (here and below)
</blockquote></details>

Done.
___
*[api/python/property_label.md, line 53 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Nj1t4o-hGpSqMgmK:-MOS7QZ0EXjJysJiLMW8:b3ulhxs) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L53)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We can also update the example to be:

import datacommons
datacommons.get_property_labels(...)

to match the function signature used above.
</blockquote></details>

We've discussed this on another PR and I think the interactive python shell is a great idea! I'm incorporating that into all docs.
___
*[api/python/property_label.md, line 58 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3NTBh5tHt6FyEn15-:-MOS8HifBB7NUiJqo7Wn:bb4eiit) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L58)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

The raw vs parsed distinction isn't required for python api's, since we always return parsed results
</blockquote></details>

Reorganized.
___
*[api/python/property_label.md, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3ODaR5X2TWZUZfmIe:-MOS8SMK6DD3hhm6jRMu:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L114)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

> ```
> If there is no value
> ```
If there are no nodes

Also, we should update the example since those are actually valid nodes.
</blockquote></details>

Done.

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/108)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/python/property_label.md, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Mnpu8Y8-81wQFk2v:-MQowYOx7fgeWbogtc1U:bb6n837) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L33)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I broke this up into a bullet point, as suggested.
Eventually I would prefer for Figure 1 to be in the glossary, but until that PR gets approved, I'm duplicating definitions and figures to every location where they are needed. So I went ahead and added Figure 1 here--let me know what you think!
</blockquote></details>

I think we can keep here
___
*[api/python/property_label.md, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3ODaR5X2TWZUZfmIe:-MQslXdv7G-RiGRwPULN:b-uhdtii) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L114)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I don't see the update here...
___
*[api/python/property_label.md, line 9 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MQow0mQ9ndo1d-5x43C:-MQow0mQ9ndo1d-5x43D:b-x6lw0q) ([raw file](https://github.com/datacommonsorg/docsite/blob/1bdf74d88e8a2b36860e7532d021970c2c078948/api/python/property_label.md#L9)):*
> ```Markdown
> ---
> 
> # Show Property Labels of Node(s)
> ```

"Retrieve" instead of "show" for consistency with REST

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/108)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @beets and @tjann)

___
*[api/python/property_label.md, line 33 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3Mnpu8Y8-81wQFk2v:-MQu3-uSDT2NN73wEUb2:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L33)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

I think we can keep here
</blockquote></details>

Done.
___
*[api/python/property_label.md, line 114 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MO3ODaR5X2TWZUZfmIe:-MQu39hBE2tixP00zy80:b-jop947) ([raw file](https://github.com/datacommonsorg/docsite/blob/1fca2bf49008a506cc8a5d731d977c39f253a212/api/python/property_label.md#L114)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Sorry, I don't see the update here...
</blockquote></details>

Sorry--is this what you were looking for?
___
*[api/python/property_label.md, line 9 at r2](https://reviewable.io/reviews/datacommonsorg/docsite/108#-MQow0mQ9ndo1d-5x43C:-MQu2ywcBnV39qX9pLH1:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/1bdf74d88e8a2b36860e7532d021970c2c078948/api/python/property_label.md#L9)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

"Retrieve" instead of "show" for consistency with REST
</blockquote></details>

Done.

**Review by beets — APPROVED** [review]
thanks!

**Pull request merged**
