### PR TITLE
Updating the REST API docs for the triple endpoint

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104)

### CODE REVIEW

**Review by beets — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/triple.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MO3J0uV0wK1grtyve60:-MO3J0uV0wK1grtyve61:b-hr1hx9) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L36)):*
> ```Markdown
>     associated with nodes linked by that property to fetch, up to *500*.
> 
> *   `key`: Your API key.
> ```

We've removed references to API key sitewide, this should be updated when you pull in recent changes from HEAD
___
*[api/rest/triple.md, line 67 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MO3JaGZ8otaC3fVpq-G:-MO3JaGZ8otaC3fVpq-H:bi3dgmw) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L67)):*
> ```Markdown
> {
>     "<dcid>": {
>         <Triples>
> ```

We should add documentation on what the shape of triples could look like.

These are the possible keys in the returned object (note that the json keys are used):
https://github.com/datacommonsorg/mixer/blob/308982c09a9e128b6af34766f3651a1e4cdb5e7f/server/model.go#L23

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/triple.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MO3J0uV0wK1grtyve60:-MO9urzCEbOFhDay_6lC:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L36)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We've removed references to API key sitewide, this should be updated when you pull in recent changes from HEAD
</blockquote></details>

Done.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @beets and @tjann)

___
*[api/rest/triple.md, line 67 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MO3JaGZ8otaC3fVpq-G:-MOEWcl72h0r3nvT0M6Y:b-k8qbh1) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L67)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We should add documentation on what the shape of triples could look like.

These are the possible keys in the returned object (note that the json keys are used):
https://github.com/datacommonsorg/mixer/blob/308982c09a9e128b6af34766f3651a1e4cdb5e7f/server/model.go#L23


</blockquote></details>

I added documentation of that list to this section; I'm not exactly sure what you were looking for though--let me know what you'd like to see!

**Review by beets — CHANGES_REQUESTED** [review]
Thanks for the update. Some requested changes... thanks!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104#-:-MQIw035CuwJ-oAgcnm1:btg5w0e)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/triple.md, line 36 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MO3J0uV0wK1grtyve60:-MO8pFzB8ItK2AzCgVlB:b-am468v) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L36)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

We've removed references to API key sitewide, this should be updated when you pull in recent changes from HEAD
</blockquote></details>

thanks for the update
___
*[api/rest/triple.md, line 42 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MQIvqHq0swglKfRnaWu:-MQIvqHq0swglKfRnaWv:b-dnbece) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L42)):*
> ```Markdown
> ### Step 1: assembling the information you will need
> 
> This endpoint requires the argument `dcids`, which are unique node identifiers defined by Data Commons. Your query will need to specify the DCIDs for the nodes of interest.
> ```

Could you please update this to match other files we've updated now that the glossary is in?
___
*[api/rest/triple.md, line 67 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MO3JaGZ8otaC3fVpq-G:-MQIuzZ97a7xykllB7Gi:beyupxh) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L67)):*
<details><summary><i>Previously, KilimAnnejaro (Anne E. Ulrich) wrote…</i></summary><blockquote>

I added documentation of that list to this section; I'm not exactly sure what you were looking for though--let me know what you'd like to see!
</blockquote></details>

I was thinking of specifying what expected keys were in the returned object, i.e. expanding out <Triples>. For now, could we list out possible keys (those would be subjectId, subjectName, etc from the file above and in the current version of the file). And please add a TODO comment to expand that out further

{# TODO: Add expanded documentation about returned object #}.

**Review by KilimAnnejaro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

___
*[api/rest/triple.md, line 42 at r1](https://reviewable.io/reviews/datacommonsorg/docsite/104#-MQIvqHq0swglKfRnaWu:-MQQIEp4AY9T5qoiGGQW:b-896fix) ([raw file](https://github.com/datacommonsorg/docsite/blob/3da9bffb015d73f8991a28aaf936528a3c291a63/api/rest/triple.md#L42)):*
<details><summary><i>Previously, beets wrote…</i></summary><blockquote>

Could you please update this to match other files we've updated now that the glossary is in?
</blockquote></details>

Done.

**Review by beets — APPROVED** [review]
Looks great, thanks for the updates!

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/docsite/104#-:-MQTqfR1E_mlIE-lLVy9:b-3oegzg)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @beets, @KilimAnnejaro, and @tjann)

**Pull request merged**
