### PR TITLE
Add LLM paper and one-sentence summaries for both

### PR DESCRIPTION
**Pull request by kmoscoe**

### CODE REVIEW

**Comment by kmoscoe** [comment]
Add link to LLM paper and add summaries to both. Link to PDF still pending.

**Review by premr — COMMENTED** [review]
Can we also have instructions on how to Cite each paper underneath ?

**Comment by kmoscoe** [comment]
Sure, if you tell me what they are. :-)

**Review by premr — APPROVED** [review]
LGTM

**Pull request merged**
